# Generated by Django 4.1.7 on 2023-03-08 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('public', 'Public'), ('economic', 'Economic'), ('finance', 'Finance'), ('technology', 'Technology'), ('sports', 'Sports'), ('custom', 'Custom')], max_length=10)),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deliverable', models.CharField(blank=True, max_length=100, null=True)),
                ('visualization', models.BooleanField(default=False)),
                ('guaranteed_submissions', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('live_presentations', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumFeature',
            fields=[
                ('premium_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('rank', models.IntegerField()),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('file_uri', models.CharField(max_length=100)),
                ('count_of_downloads', models.IntegerField(default=0)),
                ('count_of_competitions', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('contestant_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.competition')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTag',
            fields=[
                ('competition_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.competition')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionSolution',
            fields=[
                ('competition_solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_uri', models.CharField(max_length=100)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.competition')),
                ('contestant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.contestant')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionFeature',
            fields=[
                ('competition_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.competition')),
                ('premium_feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.premiumfeature')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionDataset',
            fields=[
                ('competition_dataset_id', models.AutoField(primary_key=True, serialize=False)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.competition')),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
