# Generated by Django 4.1.7 on 2023-03-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumfeature',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='competition',
            name='deliverable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competitionsolution',
            name='submission_uri',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
