# Generated by Django 4.1.7 on 2023-03-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_dataset_count_of_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='rules',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
