# Generated by Django 4.1.7 on 2023-03-19 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_competition_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='banner_uri',
            field=models.CharField(default='https://datadocketdev.blob.core.windows.net/container1/default_db_img.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='competition',
            name='rules',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dataset',
            name='banner_uri',
            field=models.CharField(default='https://datadocketdev.blob.core.windows.net/container1/default_db_img.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='file_uri',
            field=models.CharField(max_length=255),
        ),
    ]
