# Generated by Django 4.1.7 on 2023-03-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_competition_banner_uri_competition_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
