# Generated by Django 4.1.7 on 2023-04-09 15:13

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0009_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='winners_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CompetitionFeature',
        ),
        migrations.DeleteModel(
            name='PremiumFeature',
        ),
    ]
